<!DOCTYPE html>
	<head>
		<title>INFO - ON</title>
		<link rel = "icon" type = "imagens/png" href = "imagens/logo_1.png"><!--Icone Title-->
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<link rel="stylesheet" href="css/style_info_on.css">
	</head>		
	<body>
		<div class="grid-container">	
			<div class="item1">
				<img src="imagens/logo_1.png" alt="logotipo" style="width:400px;height:400px;">
			</div>
			<div class="item2">
				<h1 style="text-align: left; padding-left: 4vw">Menu Inicial</h1>
				<form action="cursos.html">
					<button type="submit">Cursos</button>
				</form>
				<form action="sobre.html">
					<button type="submit">Sobre</button>
				</form>
				<form action="contato.html">
					<button type="submit">Contato</button>
				</form>
				<form action="numerovisitas.php">
					<button type="submit">Nossas avaliações</button>
				</form>
				<form action="cadastro.html">
					<button type="submit">Cadastrar-se</button>
				</form>
				<form action="login.html">
					<button type="submit">Login</button>
				</form>
			</div>
			<div class="item3">
				<b><p style = "font-family:verdana">LOCALIZAÇÃO</p></b>
				<b><p style = "font-family: 'Courier New'">(Rua João Dias, 235 - Jardim Benardim - Vicente dos Palmares/SP) </p></b>
				<br>
				<p style="font-size:80%;font-family: 'Courier New';color: #B6922E" align="center">Número de acessos:
				<img align="center" src= "contador.php"></p>
			</div>
		</div>
	</body>
</html>